#!/usr/bin/python

# iVisDesigner
# Author: Donghao Ren, PKUVIS, Peking University, 2013.04
# See LICENSE.txt for copyright information.

execfile("version.py")

Meta("version", IV_version)
Meta("revision", IV_rev)

CSS("toolkit.css", ["styles/toolkit.less"])

Javascript("libraries.js", [
    #"libraries/jquery-1.9.1.js"
    "libraries/jquery-2.0.0-beta3.js",
    "libraries/js-yaml.js"
])

Javascript("toolkit.js", [
    "scripts/utils.js",
    "scripts/panel.js",
    "scripts/menu.js",
    "scripts/toolkit.js"
])

Image("imgs/panel.png", "images/panel.png")
Image("imgs/corner.svg", "images/corner.svg")
Image("imgs/cross.svg", "images/cross.svg")
Image("imgs/stroke.svg", "images/stroke.svg")
Image("imgs/mark.svg", "images/mark.svg")
Image("imgs/logo.svg", "images/logo.svg")

# Image("imgs/types_number.svg", "images/types_number.svg")
# Image("imgs/types_object.svg", "images/types_object.svg")
# Image("imgs/types_collection.svg", "images/types_collection.svg")
# Image("imgs/types_sequence.svg", "images/types_sequence.svg")

Binary("datasets/cardata.schema", "datasets/cardata.yaml");
Binary("datasets/cardata.data", "datasets/cardata.data.yaml");

HTML("toolkit.html", "toolkit.html")
HTML("credits.html", "credits.html")
HTML("license.html", "license.html")

WriteDeployList("deploy_list")
