#!/usr/bin/python

# iVisDesigner
# Author: Donghao Ren, PKUVIS, Peking University, 2013.04
# See LICENSE.txt for copyright information.

execfile("version.py")

Meta("version", IV_version)
Meta("revision", IV_rev.upper())

CSS("toolkit.css", ["styles/toolkit.less", "styles/font-awesome.css", "images/iconfont/ivfont.css"])

from iconfont import CreateIconFont

def iconfont_build_function(target, source, env):
    t = str(target[0])
    s = [ str(x) for x in source ]
    CreateIconFont(env["name"], s, t)
env.Append(BUILDERS = { "IconFont": Builder(action = iconfont_build_function) })

env.IconFont("images/iconfont/ivfont.css",
             FindFiles("*.svg", "images/iconfont"),
             name = "iVisDesignerIcons")


Javascript("libraries.js", [
    #"libraries/jquery-1.9.1.js"
    "libraries/jquery-2.0.0-beta3.js",
    "libraries/js-yaml.js",
    "libraries/chroma.js"
])

Javascript("toolkit.js", [
    "scripts/utils.js",
    "scripts/panel.js",
    "scripts/menu.js",
    "scripts/controls.js",
    "scripts/toolkit.js"
])

Image("imgs/panel.png", "images/panel.png")
Image("imgs/corner.svg", "images/corner.svg")
Image("imgs/logo.svg", "images/logo.svg")

Binary("datasets/cardata.schema", "datasets/cardata.yaml");
Binary("datasets/cardata.data", "datasets/cardata.data.yaml");
Binary("datasets/temperature.schema", "datasets/temperature.yaml");
Binary("datasets/temperature.data", "datasets/temperature.data.yaml");

HTML("toolkit.html", "toolkit.html")
HTML("credits.html", "credits.html")
HTML("license.html", "license.html")

WriteDeployList("deploy_list")
